<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="TestForm.aspx.cs" Inherits="SignalR_Chrome_Issues.TestForm" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Chrome SignalR Testing...</title>

    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="/Scripts/jquery-1.6.4.min.js" ></script>
    <!--Reference the SignalR library. -->
    <script src="/Scripts/jquery.signalR-1.1.3.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>

    <!--Script to update the page and send messages.--> 
    <script>
        $(function () {
            // Declare a proxy to reference the hub. 
            var chat = $.connection.chatHub;

            // Create a function that the hub can call to broadcast messages.
            chat.client.broadcastMessage = function (message) {
                // Html encode display message. 
                var encodedMsg = $('<div />').text(message).html();
                // Add the message to the page. 
                $('#progressmsgs').append('<li>' + encodedMsg + '</li>');
            };

            //Set the logging for the browser console
            $.connection.hub.logging = true;

            // Start the connection.
            $.connection.hub.start().done(function () {
                //Set the hidden field with the connection id so we can send messages to each client
                $('#contextid').val($.connection.hub.id);
            }).fail(function (e) {
                //Log errors
                console.warn(e);
            });
        });
    </script>
</head>
<body>
    <form id="form1" runat="server" style="height:100%">
         &nbsp;&nbsp;
         <font size="6"> Press the button to generate a server message back to the client. </font>
         
        <%-- The container for the messages sent to the client --%>
        <ul id="progressmsgs">
        </ul>

        <%-- Hidden connection id for SignalR --%>
        <input type="hidden" id="contextid" runat="server" />

        <%-- Button --%>
        <asp:Button ID="btnGo" runat="server" Text="Generate Messages" OnClick="btnGo_Click"/>
    </form>
</body>
</html>
